### ISSUE TITLE
No such file or directory: './dump\first_eval\5mqaq8pt0a\params.pkl'

### ISSUE THREAD

**Issue by yuy01** [facebookresearch/SymbolicMathematics#13]
- **Instruction is as follows:**
python main.py --exp_name first_eval --eval_only true --reload_model "./fwd_bwd_ibp.pth" --reload_data "./prim_ibp.test" --beam_eval true --beam_size 10 --emb_dim 1024
--n_enc_layers 6 --n_dec_layers 6 --n_heads 8 --dump_path ./dump

- **The error record is as follows:**
Traceback (most recent call last):
File "main.py", line 232, in
main(params)
File "main.py", line 156, in main
logger = initialize_exp(params)
File "D:\code\python\SymbolicMathematics\src\utils.py", line 57, in initialize_exp
pickle.dump(params, open(os.path.join(params.dump_path, 'params.pkl'), 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: './dump\first_eval\5mqaq8pt0a\params.pkl'

**Comment by f-charton** [comment]
The --dump_path parameter (and reload_path too) want an absolute path, like d:/Users/myname/dumped. 
This should solve the issue with the pickle file.

You can also avoid the random experiment names by specifying one with exp_id,
e.g. parameters
-- dump_path d:/dumped --exp_name bwd_gen --exp_id first
should send all files (pickle, train.log and data.prefix files) into
d:/dumped/bwd_gen/first/
